services:
  traefik:
    image: traefik:v2.10
    container_name: traefik-golden-egg
    restart: unless-stopped
    ports:
      - "0.0.0.0:8085:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/config:ro
    networks:
      - net-golden-egg

  mysql:
    image: mysql:8.0
    container_name: mysql-golden-egg
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goldenegg_db
      MYSQL_USER: goldenuser
      MYSQL_PASSWORD: goldenpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net-golden-egg
    labels:
      - "traefik.enable=false"

  adminer:
    image: adminer:latest
    container_name: adminer-golden-egg
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-golden-egg
      - ADMINER_DESIGN=flat
    networks:
      - net-golden-egg
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=web"

  api:
    build:
      context: ./Golden_Egg
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://goldenuser:goldenpass@mysql-golden-egg:3306/goldenegg_db
    networks:
      - net-golden-egg
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.sticky=true"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.api-strip.stripprefix.forceSlash=false"
      - "traefik.http.routers.api.middlewares=api-strip@docker"
      - "traefik.http.middlewares.api-headers.headers.customrequestheaders.X-Forwarded-Prefix=/api"

networks:
  net-golden-egg:
    driver: bridge

volumes:
  mysql_data: