FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=goldenegg_db
ENV MYSQL_USER=goldenuser
ENV MYSQL_PASSWORD=goldenpass

# Exponer el puerto estándar de MySQL
EXPOSE 3306
